# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    method: 'GET'
    headers: |
      {
      "Content-Type":"application/json"
      }
    urlSuffix: 'http://worldclockapi.com/api/json/est/now'
    waitForCompletion: 'false'
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
